on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Org Name'
        required: true
        default: 'Test Org'
        type: choice
        options:
        - Test Org
        - XXX Org
        - Deneme Org
      projectName:
        description: 'Project Name'
        required: true
      workItemType:
        description: 'Work Item Type'
        required: true
        default: 'User Story'
        type: choice
        options:
          - User Story
          - Feature
          - Bugs
      ruleType:
        description: 'Rule Type'
        required: true
        default: 'Mandatary Wrok ID'
        type: choice
        options:
          - Mandatory Work ID
          - Mandatory InvestmentDimension
          - StoryPointsPicklist
          - StoryPointsPicklistReverse
      stageCategory:
        description: 'Stage'
        required: true
        default: 'N/A'
        type: choice
        options:
          - N/A
          - InProgress
          - Complated

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - run: |
          echo "Org: $ORG"
          echo "Project: $PROJECTNAME"
          echo "Wrok Item Type: $WROKITEMTYPE"
          echo "Rule Type: $RULETYPE"
          echo "Log level: $STATECATEGORY"
        env:
          ORG: ${{ inputs.org }}
          PROJECTNAME: ${{ inputs.projectName }} 
          WROKITEMTYPE: ${{ inputs.workItemType }} 
          RULETYPE: ${{ inputs.ruleType }} 
          STATECATEGORY: ${{ inputs.stageCategory }} 









          
