on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      projectName:
        description: 'Project Name'
        required: true

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Log level: $PROJECTNAME"
        env:
          LEVEL: ${{ inputs.logLevel }}
          PROJECTNAME: ${{ inputs.projectName }}
